sylius_grid:
    grids:
        sylius_admin_inventory:
            fields:
                inventory:
                    enabled: false
                current_stock:
                    type: twig
                    path: .
                    label: sylius.ui.current_stock
                    options:
                        template: "@MangoSyliusInventoryUpdatePlugin/SyliusAdmin/Inventory/Grid/Field/currentStock.html.twig"
                reserved:
                    type: twig
                    path: .
                    label: sylius.ui.reserved
                    options:
                        template: "@MangoSyliusInventoryUpdatePlugin/SyliusAdmin/Inventory/Grid/Field/reserved.html.twig"
            actions:
                main:
                    update_inventory:
                        type: update_variant_inventory
    templates:
        action:
            update_variant_inventory: "@MangoSyliusInventoryUpdatePlugin/SyliusAdmin/Inventory/Grid/Action/updateInventory.html.twig"
