mango_sylius_admin_inventory_update:
    path: inventory/update
    methods: [PUT]
    defaults:
        _controller: MangoSylius\InventoryUpdatePlugin\Controller\MangoProductVariantController:saveInventoryAction
        _format: json
        _sylius:
            permission: true
